spring:
  application:
    name: "spring-cloud-stream-kafka-streams-processor"
  cloud:
    function:
      definition: userStateStream
    stream:
      bindings:
        userStateStream-in-0:
          destination: "pub.user.token"
        userStateStream-out-0:
          destination: "pub.user.state"
      kafka:
        streams:
          binder:
            applicationId: "${spring.application.name}"
            brokers: "localhost:9094"
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

user:
  schedule: PT5S
  expiration: PT60S
